// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhSteOI8S_xN2HwNo-1yK2OQGWa7bSeD4',
    appId: '1:363132590106:web:19c9ef797f1bbc7ab559a3',
    messagingSenderId: '363132590106',
    projectId: 'mobile-application-55116',
    authDomain: 'mobile-application-55116.firebaseapp.com',
    storageBucket: 'mobile-application-55116.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOzj-eFITFm6BdIMgjLb9hkz8lrpRxyyU',
    appId: '1:363132590106:android:612134bf7fbc2fbbb559a3',
    messagingSenderId: '363132590106',
    projectId: 'mobile-application-55116',
    storageBucket: 'mobile-application-55116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkBDd-D3A78-iG_ry7WWd62bG1I3Bvx0Q',
    appId: '1:363132590106:ios:7ee4641d1ba70573b559a3',
    messagingSenderId: '363132590106',
    projectId: 'mobile-application-55116',
    storageBucket: 'mobile-application-55116.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkBDd-D3A78-iG_ry7WWd62bG1I3Bvx0Q',
    appId: '1:363132590106:ios:4795993175ffe11fb559a3',
    messagingSenderId: '363132590106',
    projectId: 'mobile-application-55116',
    storageBucket: 'mobile-application-55116.appspot.com',
    iosBundleId: 'com.example.mobileApp.RunnerTests',
  );
}
